
version: '2'

volumes:
  peer0.contoso.example.com:
  peer1.contoso.example.com:

networks:
  acme:

services:

  peer0.contoso.example.com:
    container_name: peer0.contoso.example.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_acme
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific config
      - CORE_PEER_ID=peer0.contoso.example.com
      - CORE_PEER_ADDRESS=peer0.contoso.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.contoso.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.contoso.example.com:7051
      - CORE_PEER_LOCALMSPID=ContosoMSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - $HYPERLEDGER_HOME/data/crypto-config/peerOrganizations/contoso.example.com/peers/peer0.contoso.example.com/msp:/etc/hyperledger/fabric/msp
        - $HYPERLEDGER_HOME/data/crypto-config/peerOrganizations/contoso.example.com/peers/peer0.contoso.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.contoso.example.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
    networks:
      - acme

  peer1.contoso.example.com:
    container_name: peer1.contoso.example.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_acme
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific config
      - CORE_PEER_ID=peer1.contoso.example.com
      - CORE_PEER_ADDRESS=peer1.contoso.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.contoso.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.contoso.example.com:7051
      - CORE_PEER_LOCALMSPID=ContosoMSP
    volumes:
        - /var/run/:/host/var/run/
        - $HYPERLEDGER_HOME/data/crypto-config/peerOrganizations/contoso.example.com/peers/peer1.contoso.example.com/msp:/etc/hyperledger/fabric/msp
        - $HYPERLEDGER_HOME/data/crypto-config/peerOrganizations/contoso.example.com/peers/peer1.contoso.example.com/tls:/etc/hyperledger/fabric/tls
        - peer1.contoso.example.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
    networks:
      - acme

#  cli-contoso:
#    container_name: cli-contoso
#    image: hyperledger/fabric-tools:$IMAGE_TAG
#    tty: true
#    stdin_open: true
#    environment:
#      - GOPATH=/opt/gopath
#      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#      #- CORE_LOGGING_LEVEL=DEBUG
#      - CORE_LOGGING_LEVEL=INFO
#      - CORE_PEER_ID=cli-contoso
#      - CORE_PEER_ADDRESS=peer0.contoso.example.com:7051
#      - CORE_PEER_LOCALMSPID=ContosoMSP
#      - CORE_PEER_TLS_ENABLED=true
#      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/contoso.example.com/peers/peer0.contoso.example.com/tls/server.crt
#      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/contoso.example.com/peers/peer0.contoso.example.com/tls/server.key
#      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/contoso.example.com/peers/peer0.contoso.example.com/tls/ca.crt
#      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/contoso.example.com/users/Admin@contoso.example.com/msp
#    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
#    command: /bin/bash
#    volumes:
#        - /var/run/:/host/var/run/
#        - $HYPERLEDGER_HOME/code/chaincode/:/opt/gopath/src/github.com/chaincode
#        - $HYPERLEDGER_HOME/data/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
#        - $HYPERLEDGER_HOME/code/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
#        - $HYPERLEDGER_HOME/data/channel-def:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
#    depends_on:
#      - peer0.contoso.example.com
#      - peer1.contoso.example.com
#    networks:
#      - acme
#
#
