
version: '2'

volumes:
  orderer.acme.example.com:
  peer0.acme.example.com:
  peer1.acme.example.com:

networks:
  acme:

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - $HYPERLEDGER_HOME/data/channel-def/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - $HYPERLEDGER_HOME/data/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - $HYPERLEDGER_HOME/data/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    - orderer.acme.example.com:/var/hyperledger/production
    ports:
      - 7050:7050
    networks:
      - acme


  peer0.acme.example.com:
    container_name: peer0.acme.example.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_acme
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific config
      - CORE_PEER_ID=peer0.acme.example.com
      - CORE_PEER_ADDRESS=peer0.acme.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.acme.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.acme.example.com:7051
      - CORE_PEER_LOCALMSPID=AcmeMSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - $HYPERLEDGER_HOME/data/crypto-config/peerOrganizations/acme.example.com/peers/peer0.acme.example.com/msp:/etc/hyperledger/fabric/msp
        - $HYPERLEDGER_HOME/data/crypto-config/peerOrganizations/acme.example.com/peers/peer0.acme.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.acme.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - acme

  peer1.acme.example.com:
    container_name: peer1.acme.example.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_acme
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific config
      - CORE_PEER_ID=peer1.acme.example.com
      - CORE_PEER_ADDRESS=peer1.acme.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.acme.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.acme.example.com:7051
      - CORE_PEER_LOCALMSPID=AcmeMSP
    volumes:
        - /var/run/:/host/var/run/
        - $HYPERLEDGER_HOME/data/crypto-config/peerOrganizations/acme.example.com/peers/peer1.acme.example.com/msp:/etc/hyperledger/fabric/msp
        - $HYPERLEDGER_HOME/data/crypto-config/peerOrganizations/acme.example.com/peers/peer1.acme.example.com/tls:/etc/hyperledger/fabric/tls
        - peer1.acme.example.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053
    networks:
      - acme

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      # Override with setEnv.sh
      - CORE_PEER_ADDRESS=peer0.acme.example.com:7051
      - CORE_PEER_LOCALMSPID=AcmeMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/acme.example.com/peers/peer0.acme.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/acme.example.com/peers/peer0.acme.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/acme.example.com/peers/peer0.acme.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/acme.example.com/users/Admin@acme.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - $HYPERLEDGER_HOME/code/chaincode/:/opt/gopath/src/github.com/chaincode
        - $HYPERLEDGER_HOME/data/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - $HYPERLEDGER_HOME/code/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - $HYPERLEDGER_HOME/code/chaincode:/opt/gopath/src/github.com/hyperledger/fabric/peer/code/
        - $HYPERLEDGER_HOME/data/channel-def:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.acme.example.com
      - peer1.acme.example.com
    networks:
      - acme


